{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "240347a3-4589-4419-bf6a-bf94199b9901",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "pipeline.py - Main orchestrator for the Automated Weather Data Pipeline\n",
    "Calls api_client to fetch weather data and storage to save results.\n",
    "\"\"\"\n",
    "\n",
    "import logging\n",
    "import os\n",
    "from datetime import datetime\n",
    "\n",
    "# Configure logging\n",
    "os.makedirs(\"logs\", exist_ok=True)\n",
    "logging.basicConfig(\n",
    "    level=logging.INFO,\n",
    "    format=\"%(asctime)s [%(levelname)s] %(message)s\",\n",
    "    handlers=[\n",
    "        logging.FileHandler(\"logs/pipeline.log\"),\n",
    "        logging.StreamHandler()\n",
    "    ]\n",
    ")\n",
    "logger = logging.getLogger(__name__)\n",
    "\n",
    "# Import teammates' modules (they will implement these)\n",
    "try:\n",
    "    from api_client import fetch_weather_for_cities\n",
    "except ImportError:\n",
    "    logger.error(\"api_client.py not found. Make sure your teammate has implemented it.\")\n",
    "    raise\n",
    "\n",
    "try:\n",
    "    from storage import save_to_csv, save_to_sqlite\n",
    "except ImportError:\n",
    "    logger.error(\"storage.py not found. Make sure your teammate has implemented it.\")\n",
    "    raise\n",
    "\n",
    "\n",
    "# Cities to track\n",
    "CITIES = [\n",
    "    {\"name\": \"Tallahassee\", \"latitude\": 30.4518, \"longitude\": -84.2807},\n",
    "    {\"name\": \"Miami\",       \"latitude\": 25.7617, \"longitude\": -80.1918},\n",
    "    {\"name\": \"Orlando\",     \"latitude\": 28.5383, \"longitude\": -81.3792},\n",
    "    {\"name\": \"Tampa\",       \"latitude\": 27.9506, \"longitude\": -82.4572},\n",
    "]\n",
    "\n",
    "CSV_PATH    = \"data/processed/weather_data.csv\"\n",
    "SQLITE_PATH = \"data/processed/weather_data.db\"\n",
    "\n",
    "\n",
    "def run_pipeline():\n",
    "    \"\"\"Main pipeline function: fetch → process → store.\"\"\"\n",
    "    logger.info(\"=\" * 50)\n",
    "    logger.info(f\"Pipeline run started at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\")\n",
    "    logger.info(\"=\" * 50)\n",
    "\n",
    "    # Step 1: Fetch data from API\n",
    "    logger.info(f\"Fetching weather data for {len(CITIES)} cities...\")\n",
    "    records = fetch_weather_for_cities(CITIES)\n",
    "\n",
    "    if not records:\n",
    "        logger.warning(\"No records fetched. Exiting pipeline.\")\n",
    "        return\n",
    "\n",
    "    logger.info(f\"Successfully fetched {len(records)} records.\")\n",
    "\n",
    "    # Step 2: Save to CSV\n",
    "    logger.info(f\"Saving records to CSV: {CSV_PATH}\")\n",
    "    save_to_csv(records, CSV_PATH)\n",
    "\n",
    "    # Step 3: Save to SQLite\n",
    "    logger.info(f\"Saving records to SQLite: {SQLITE_PATH}\")\n",
    "    save_to_sqlite(records, SQLITE_PATH)\n",
    "\n",
    "    logger.info(\"Pipeline run completed successfully.\")\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    run_pipeline()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
