# Generated by Django 6.0.4 on 2026-04-20 03:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('records_fetched', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=100, unique=True)),
                ('track_name', models.CharField(max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('popularity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('danceability', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('energy', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('tempo', models.FloatField()),
                ('loudness', models.FloatField()),
                ('valence', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('duration_ms', models.IntegerField()),
                ('explicit', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('csv', 'CSV Import'), ('api', 'API Fetch')], default='csv', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='spotifyapp.genre')),
            ],
            options={
                'ordering': ['-popularity'],
                'indexes': [models.Index(fields=['genre'], name='spotifyapp__genre_i_5a52b7_idx'), models.Index(fields=['popularity'], name='spotifyapp__popular_fc4a33_idx')],
            },
        ),
    ]
